import { DependencyScan, DependencyScanItem, Project } from './models';

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'checkout-service',
    userId: 'demo-user',
    name: 'checkout-service',
    description: 'Backend API for checkout and order processing.',
    packageManager: 'npm',
    scheduleType: 'weekly',
    lastScanAt: '2026-05-07T09:41:00Z',
    lastHealthScore: 82,
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-05-07T09:41:00Z',
  },
  {
    id: 'web-frontend',
    userId: 'demo-user',
    name: 'web-frontend',
    description: 'Customer web application.',
    packageManager: 'yarn',
    scheduleType: 'weekly',
    lastScanAt: '2026-05-06T19:05:00Z',
    lastHealthScore: 76,
    createdAt: '2026-04-12T10:00:00Z',
    updatedAt: '2026-05-06T19:05:00Z',
  },
  {
    id: 'payment-gateway',
    userId: 'demo-user',
    name: 'payment-gateway',
    description: 'Payment processing API.',
    packageManager: 'npm',
    scheduleType: 'weekly',
    lastScanAt: '2026-05-06T15:20:00Z',
    lastHealthScore: 43,
    createdAt: '2026-04-17T10:00:00Z',
    updatedAt: '2026-05-06T15:20:00Z',
  },
];

export const DEMO_SCANS: DependencyScan[] = [
  {
    id: 'scan-demo-1',
    projectId: 'checkout-service',
    userId: 'demo-user',
    status: 'completed',
    healthScore: 82,
    totalDependencies: 312,
    totalDevDependencies: 170,
    outdatedCount: 68,
    vulnerableCount: 3,
    deprecatedCount: 2,
    abandonedCount: 4,
    criticalRiskCount: 0,
    highRiskCount: 5,
    mediumRiskCount: 20,
    lowRiskCount: 45,
    createdAt: '2026-05-07T09:41:00Z',
  },
  {
    id: 'scan-demo-2',
    projectId: 'web-frontend',
    userId: 'demo-user',
    status: 'completed',
    healthScore: 76,
    totalDependencies: 712,
    totalDevDependencies: 390,
    outdatedCount: 104,
    vulnerableCount: 7,
    deprecatedCount: 5,
    abandonedCount: 8,
    criticalRiskCount: 0,
    highRiskCount: 7,
    mediumRiskCount: 28,
    lowRiskCount: 61,
    createdAt: '2026-05-06T19:05:00Z',
  },
  {
    id: 'scan-demo-3',
    projectId: 'payment-gateway',
    userId: 'demo-user',
    status: 'failed',
    healthScore: 43,
    totalDependencies: 601,
    totalDevDependencies: 322,
    outdatedCount: 146,
    vulnerableCount: 12,
    deprecatedCount: 6,
    abandonedCount: 11,
    criticalRiskCount: 3,
    highRiskCount: 25,
    mediumRiskCount: 52,
    lowRiskCount: 44,
    createdAt: '2026-05-06T15:20:00Z',
  },
];

export const DEMO_ITEMS: DependencyScanItem[] = [
  {
    id: 'item-axios',
    scanId: 'scan-demo-1',
    projectId: 'checkout-service',
    userId: 'demo-user',
    packageName: 'axios',
    currentRange: '^0.21.1',
    currentVersion: '0.21.1',
    latestVersion: '1.6.8',
    dependencyType: 'dependency',
    updateType: 'major',
    riskLevel: 'high',
    riskScore: 82,
    isOutdated: true,
    isVulnerable: true,
    vulnerabilities: [
      { id: 'CVE-2023-45857', summary: 'Header injection in affected Axios versions.', severity: 'high' },
      { id: 'CVE-2023-45853', summary: 'Request handling vulnerability.', severity: 'high' },
    ],
    isDeprecated: false,
    isPossiblyAbandoned: false,
    lastPublishedAt: '2026-02-01T00:00:00Z',
    riskReason: 'Known high severity vulnerabilities affect this version.',
    aiExplanation: 'Upgrade carefully: this is a major version jump, so HTTP interceptors, cancellation, and error handling should be regression tested.',
    recommendedAction: 'Update axios to 1.6.8 and run integration tests around API calls.',
    updateCommand: 'npm install axios@1.6.8',
    npmUrl: 'https://www.npmjs.com/package/axios',
    repositoryUrl: 'https://github.com/axios/axios',
  },
  {
    id: 'item-lodash',
    scanId: 'scan-demo-1',
    projectId: 'checkout-service',
    userId: 'demo-user',
    packageName: 'lodash',
    currentRange: '^4.17.15',
    currentVersion: '4.17.15',
    latestVersion: '4.17.21',
    dependencyType: 'dependency',
    updateType: 'patch',
    riskLevel: 'critical',
    riskScore: 95,
    isOutdated: true,
    isVulnerable: true,
    vulnerabilities: [{ id: 'CVE-2021-23337', summary: 'Command injection in lodash template.', severity: 'critical' }],
    isDeprecated: false,
    isPossiblyAbandoned: false,
    lastPublishedAt: '2021-02-20T00:00:00Z',
    riskReason: 'Critical vulnerability found in the installed range.',
    aiExplanation: 'This should be a low-friction patch update, but utility-heavy packages deserve a smoke test across formatting and object transforms.',
    recommendedAction: 'Update lodash to 4.17.21 immediately.',
    updateCommand: 'npm install lodash@4.17.21',
    npmUrl: 'https://www.npmjs.com/package/lodash',
    repositoryUrl: 'https://github.com/lodash/lodash',
  },
  {
    id: 'item-express',
    scanId: 'scan-demo-1',
    projectId: 'checkout-service',
    userId: 'demo-user',
    packageName: 'express',
    currentRange: '^4.17.1',
    currentVersion: '4.17.1',
    latestVersion: '4.19.2',
    dependencyType: 'dependency',
    updateType: 'minor',
    riskLevel: 'medium',
    riskScore: 52,
    isOutdated: true,
    isVulnerable: false,
    vulnerabilities: [],
    isDeprecated: false,
    isPossiblyAbandoned: false,
    lastPublishedAt: '2026-01-12T00:00:00Z',
    riskReason: 'Minor update available with security and stability fixes.',
    aiExplanation: 'Review middleware behavior and route tests after upgrading.',
    recommendedAction: 'Plan a minor update during the next maintenance window.',
    updateCommand: 'npm install express@4.19.2',
    npmUrl: 'https://www.npmjs.com/package/express',
  },
];
